Repository arkedge/gaia, pull requests merged in 2024-04, with the labels that each got.

#126 devtools-frontend/crates is Cargo workspace
  .gitignore
  devtools-frontend/crates/Cargo.lock
Labels: invalid

#130 Fix devtools-frontend protobuf codegen path
  devtools-frontend/package.json
Labels: bug

#125 エラーメッセージを改善する
  gaia-tmtc/src/tco_tmiv/tmiv.rs
  tmtc-c2a/src/satellite.rs
Labels: enhancement

#133 kble_gsをWebSocketのgracefulな終了に対応させる
  tmtc-c2a/src/kble_gs.rs
Labels: bug
